// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DropdownController from "./dropdown_controller.js"
application.register("dropdown", DropdownController)

import EquityController from "./equity_controller.js"
application.register("equity", EquityController)

import I18nController from "./i18n_controller.js"
application.register("i18n", I18nController)

import LinkController from "./link_controller.js"
application.register("link", LinkController)

import TabsController from "./tabs_controller.js"
application.register("tabs", TabsController)
