// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import LinkController from "./link_controller.js"
application.register("link", LinkController)

import PropertyCardController from "./property_card_controller.js"
application.register("property-card", PropertyCardController)
